#!/bin/bash
set -eu

# handle data volume

data_device="/dev/disk/by-id/google-gitlab_data"
partition="${data_device}-part1"

if ! blkid "${data_device}" > /dev/null
then
    parted "${data_device}" mklabel gpt
fi

partcount=$(lsblk -n "${data_device}" | wc -l)

if [ "${partcount}" = 1 ]
then
    parted -s -a optimal "${data_device}" mkpart primary 0% 100%
    # If we're creating partitions, then we should be creating an fs too
    # I have a personal bias towards xfs, and against ext4 due to an old
    # fs full bug in ext4
    apt-get install -y xfsprogs
    mkfs.xfs -f ${partition}
    xfs_admin -L gitlab_data ${partition}
fi

if ! grep -q gitlab_data /etc/fstab
then
    echo 'LABEL=gitlab_data /var/opt/gitlab xfs defaults 0 0' >> /etc/fstab
    mkdir -p /var/opt/gitlab
fi

if ! grep -qs '/var/opt/gitlab' /proc/mounts
then
    mount /var/opt/gitlab
fi

# configure prereqs
apt-get update
echo 'postfix postfix/mailname string ${1}' | debconf-set-selections
echo 'postfix postfix/main_mailer_type string \"Internet Site\"' | debconf-set-selections
apt-get install -y curl openssh-server ca-certificates postfix
# Add GitLab repo
curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
# Install GitLab
apt-get install -y gitlab-ce
# Configure GitLab
mkdir -p /etc/gitlab
mv /tmp/gitlab.rb /etc/gitlab/gitlab.rb
chown root:root /etc/gitlab/gitlab.rb
chmod 0600 /etc/gitlab/gitlab.rb
# Check if we have an ssl key and put it in place if so.
# This assumes we also have an ssl certificate
if [ -s /tmp/ssl_key ]
then
    install -d -m 0700 /etc/gitlab/ssl
    mv /tmp/ssl_key "/etc/gitlab/ssl/${1}.key"
    mv /tmp/ssl_certificate "/etc/gitlab/ssl/${1}.crt"
fi

/opt/gitlab/bin/gitlab-ctl reconfigure
