#!/bin/bash
set -eu

# configure prereqs
yum update -y
yum install -y curl policycoreutils-python openssh-server
# Add GitLab repo
curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | bash
# Install GitLab
yum install -y gitlab-ce
