#!/bin/bash
set -eu

runner_name=${1}
runner_host=${2}
runner_token=${3}
runner_image=${4}

## Install docker
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
yum makecache fast
yum -y --enablerepo=rhui-REGION-rhel-server-extras install container-selinux
yum -y install docker-ce

# Start Docker
systemctl start docker

## Install GitLab Multi-Runner
curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.rpm.sh | bash
yum install -y gitlab-ci-multi-runner
# Configure runner
gitlab-ci-multi-runner register \
  --non-interactive \
  --url ${runner_host} \
  --registration-token ${runner_token} \
  --name ${runner_name} \
  --executor docker \
  --docker-image ${runner_image} 2>&1 >> /var/log/gitlab-ci-multi-runner.boostrap.log
